### ISSUE TITLE
Include `xmidas` package

### ISSUE THREAD

**Issue by dmgav** [nsls2-conda-envs/conda-pack-template#52]
`xmidas` (developed at HXN) package is ready to be included in the environment

**Comment by mrakitin** [comment]
There are incompatibilities of some libraries listed in the `nsls2-collection` spec with `gfortran` v9.x that is a requirement of `scipy` v1.6+. Need to resolve those before `xmidas` can be included into the environment.

**Comment by dmgav** [comment]
In 2021-1.2 (before switching to conda-forge) we had scipy v1.6.1
```
(/opt/conda_envs/collection-2021-1.2)  $ pip list | grep scipy
scipy                         1.6.1
```

**Comment by mrakitin** [comment]
Interesting... It's something to do with the conda-forge packages. I'll need to dig into it to see the root cause but may take a while.

**Comment by mrakitin** [comment]
Included in the latest conda environments.
